[package]
name = "gba"
description = "A crate (and book) for making GBA games with Rust."
version = "0.5.0-pre"
authors = ["Lokathor <zefria@gmail.com>", "Thomas Winwood <twwinwood@gmail.com>"]
repository = "https://github.com/rust-console/gba"
readme = "README.md"
keywords = ["gba"]
edition = "2018"
license = "Apache-2.0"

publish = false

[dependencies]
voladdress = "0.3"
gba-proc-macro = "0.5"

[profile.release]
lto = true
panic = "abort"
incremental = false
codegen-units = 1
